### ISSUE TITLE
Current pypi module is broken

### ISSUE THREAD

**Issue by domschl** [Esukhia/bophono#5]
Using `bophono` with `pip install bophono` fails for two reasons:

- dependency to `pypandoc` is missing
- resources are missing / inconsistent source version published

Since the module does seem to work when installed from git,

please consider republishing a complete version of `bophono`.

**Comment by eroux** [comment]
Hi @domschl I just realized I totally skipped your issue, sorry for that! @mikkokotila just opened similar issues, I hope this can be looked at soon (I'm not planning to work on this soon but if I have some free time I can give it a try)

**Comment by domschl** [comment]
While I had success installing on Linux, Windows install seems to throw an error because of the Tibetan Unicode in `README.md`:

````
PS C:\Users\dsc> pip3 install bophono
Defaulting to user installation because normal site-packages is not writeable
Collecting bophono
  Using cached bophono-0.1.2.tar.gz (28 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\dsc\AppData\Local\Temp\pip-install-w1a9623c\bophono_c9b7fac141a2439fb7d2184753de8eb9\setup.py", line 27, in <module>
          long_description=read('README.md'),
                           ^^^^^^^^^^^^^^^^^
        File "C:\Users\dsc\AppData\Local\Temp\pip-install-w1a9623c\bophono_c9b7fac141a2439fb7d2184753de8eb9\setup.py", line 15, in read
          return open(os.path.join(os.path.dirname(__file__), fname)).read()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python311\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1830: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```
I will do some more testing and report back.
